namespace KioskAppWpf.Enums
{
    public enum OpcState
    {
        PlcLifeBitOk,
        PlcLifeBitError,
        TransactionLifeBitError,
        TransactionLifeBitOk,

        OpcLiveOk,
        OpcLiveError,

        Power230Ok,
        Power230Error,
        Power24Ok,
        Power24Error,
        FlowMeterOk,
        FlowMeterError,
        DumpPathOk,
        DumpPathError,
        ScreenOk,
        ScreenError,
        ScreenFullOk,
        ScreenFullError,
        ProbeOk,
        ProbeError,
        ProbeReadyOk,
        ProbeReadyError,
        ProbeFullOk,
        ProbeFullError,
        PhMeterOk,
        PhMeterError,
        CondMeterOk,
        CondMeterError,
        TempMeterOk,
        TempMeterError,
        ChztMeterOk,
        ChztMeterError,
        PressureMeterOk,
        PressureMeterError,
        KioskDoorError,
        KioskDoorOk,
        ValveMeterError,
        ValveMeterOk,
        ZasuwaError,
        ZasuwaOk,

        ProbeDoorOpenOk,
        ProbeDoorOpenError,
        AirOk,
        AirError,
        Distribution230VACOk,
        Distribution230VACError,
        Rack230VACOk,
        Rack230VACError,
        Rack24VDCOk,
        Rack24VDCError,
        Rack24VDCUPSOk,
        Rack24VDCUPSError,
        Rack12VDCOk,
        Rack12VDCError,

        PumpRoomOk,
        PumpRoomError,
        PumpRoomWorkOk,
        PumpRoomWorkError,
        ScreenRoomLeakOk,
        ScreenRoomLeakError,
        AugerOk,
        AugerError,
        PreScreenOk,
        PreScreenError,

        AllOk,
    }
}
